[localhost]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[local]
localhost

[mongodb]
localhost

[catalogue]
localhost

[redis]
localhost

[user]
localhost

[cart]
localhost

[mysql]
localhost

[shipping]
localhost

[rabbitmq]
localhost

[payment]
localhost

[frontend]
localhost

